[package]
name = "shepr-vt"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
alacritty_terminal = { workspace = true }
memchr = { workspace = true }
shepr-core = { path = "../shepr-core" }
shepr-term = { path = "../shepr-term" }
vte = { workspace = true }

[lints]
workspace = true
