mod alt_screen_read;
pub mod autodetect;
pub(crate) mod client_accept;
pub(crate) mod client_commands;
mod client_endpoint_control;
pub(crate) mod client_shell;
pub(crate) mod client_transport;
pub(crate) mod clients;
pub mod headless;
pub(crate) mod keybindings;
pub(crate) mod pane_input;
pub(crate) mod render_stream;
pub mod socket_paths;
