[package]
name = "shepr-pty"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
bytes = { workspace = true }
libc = { workspace = true }
shepr-core = { path = "../shepr-core" }
tracing = { workspace = true }

[dev-dependencies]
shepr-test-support = { path = "../shepr-test-support" }

[lints]
workspace = true
