[package]
name = "shepr-remote"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
shepr-api = { path = "../shepr-api" }
shepr-config = { path = "../shepr-config" }
shepr-core = { path = "../shepr-core" }
shepr-platform = { path = "../shepr-platform" }
shepr-protocol = { path = "../shepr-protocol" }
tracing = { workspace = true }

[dev-dependencies]
libc = { workspace = true }
shepr-test-fixtures = { path = "../shepr-test-fixtures" }
shepr-test-support = { path = "../shepr-test-support" }

[lints]
workspace = true
