[package]
name = "shepr-protocol"
version = "0.1.0"
edition = "2024"
publish = false
build = "build.rs"

[dependencies]
ratatui = { workspace = true }
serde = { workspace = true }
shepr-config = { path = "../shepr-config" }
shepr-core = { path = "../shepr-core" }
shepr-vt = { path = "../shepr-vt" }

[dev-dependencies]
shepr-test-support = { path = "../shepr-test-support" }

[lints]
workspace = true
