[package]
name = "shepr-termio"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
base64 = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
serde = { workspace = true }
shepr-config = { path = "../shepr-config" }
shepr-core = { path = "../shepr-core" }
shepr-platform = { path = "../shepr-platform" }
shepr-protocol = { path = "../shepr-protocol" }
shepr-vt = { path = "../shepr-vt" }
tracing = { workspace = true }
unicode-width = { workspace = true }

[dev-dependencies]
toml = { workspace = true }

[lints]
workspace = true
