[package]
name = "shepr-api"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
shepr-config = { path = "../shepr-config" }
shepr-platform = { path = "../shepr-platform" }
shepr-protocol = { path = "../shepr-protocol" }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
shepr-test-support = { path = "../shepr-test-support" }

[lints]
workspace = true
