pub(in crate::shell) mod compose_pane_surface;
pub(in crate::shell) mod composition;
mod config;
pub(in crate::shell) mod render;
mod selection_render;
pub(in crate::shell) mod status;
pub(in crate::shell) mod surface_patch;
pub(in crate::shell) mod surfaces;
pub(in crate::shell) mod topology;
pub(in crate::shell) mod wire_cells;
