[package]
name = "shepr-integration"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
jsonc-parser = { workspace = true }
serde_json = { workspace = true }
shepr-agent = { path = "../shepr-agent" }
shepr-core = { path = "../shepr-core" }
shepr-platform = { path = "../shepr-platform" }
toml = { workspace = true }
toml_edit = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
libc = { workspace = true }
regex = { workspace = true }
shepr-test-support = { path = "../shepr-test-support" }

[lints]
workspace = true
